
language: perl
perl:
    - "dev"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - sudo apt-get -y remove libzmq*

install:
    - cpanm --notest Perl::PrereqScanner

before_script:
    - >-
        cp $(which scan_prereqs) ./ &&
        ./scan_prereqs --combine lib t
        | grep -v ZMQ::FFI
        | awk '{ print $1 }'
        | cpanm --notest || /bin/true

    - perl scripts/gen_modules.pl

script: xt/test_versions.sh
